### PR TITLE
Visualization documentation revisions

### PR DESCRIPTION
**Pull request by alvin-garcia**
Luke,

I fixed issues and improved clarity of the visualizations documentation. Please merge and build the documentation website. Thanks.

### CODE REVIEW

**Comment by lstagner** [comment]
Did you already build the website locally?

**Comment by alvin-garcia** [comment]
I tried, but I do not have the ford command. Did you clone the FORD repository onto your home directory or is it available on Iris?
Screen Shot 2020-08-24 at 12 33 11 PM

**Comment by lstagner** [comment]
I'll just merge it in. Afterwards check the dev website for mistakes

**Comment by lstagner** [comment]
The plots on the visualization page is still messed up.

**Comment by alvin-garcia** [comment]
Where are you looking? I don't see the updated version [here](http://d3denergetic.github.io/FIDASIM/master/page/01_getting_started/05_visual.html).

**Comment by lstagner** [comment]
There are numerous places for example
Screen Shot 2020-08-25 at 3 07 04 PM

**Comment by alvin-garcia** [comment]
That is not the updated version. "Below is a summary of examples for Case 1:" was deleted in my last commit. In other words, the website does not reflect the changes in FIDASIM/docs

**Comment by lstagner** [comment]
Oh, Looks like the website build is failing

**Comment by alvin-garcia** [comment]
Why?

**Comment by lstagner** [comment]
OK the website build is fixed now and the visualization page looks alright.

**Pull request merged**
