### PR TITLE
Add visualization scripts

### PR DESCRIPTION
**Pull request by alvin-garcia**

### CODE REVIEW

**Comment by lstagner** [comment]
Could you add documentation to the [Preprocessing Inputs](http://d3denergetic.github.io/FIDASIM/page/01_getting_started/02_preprocess.html) and  [Reading Outputs](http://d3denergetic.github.io/FIDASIM/page/01_getting_started/04_reading.html) sections detailing the basic usage of the scripts.

**Comment by lstagner** [comment]
When you think this is ready let me know and I'll merge it in.

**Comment by alvin-garcia** [comment]
It's ready.

**Comment by lstagner** [comment]
I'll merge it at end of day just in case you forgot something else.

**Pull request merged**
