### PR TITLE
Mixed Thermal Species Support

### PR DESCRIPTION
**Pull request by lstagner**
This PR implements mixed thermal species. This changes the FIDASIM input files so this is a breaking change.

The biggest change is that we no longer use quasineutrality to calculate the ion and impurity densities. The `equilibrium.h5/plasma` file now contains
```
[runid]_equilibrium.h5
├── plasma  (only showing new variables)
     ├ nthermal # number of thermal species
     ├ species_mass # Atomic mass of thermal species
     ├ impurity_charge # Charge number of the main impurity species
     ├ denimp # impurity density: denimp(r,z,[phi])
     └ deni # ion density: deni(species,r,z,[phi]) doesn't include fast-ions
```
As a result of the new equilibrium file format the ion mass and impurity charge was removed from the `[runid]_inputs.dat` file

The fast-ion correction used in the `dcx` and `halo` subroutines are now only used when the thermal and fast-ion species are the same. 

This PR is only for the thermal ions and doesn't touch the fast-ions.

### CODE REVIEW

**Comment by lstagner** [comment]
Needs Quasineutrality checks

**Comment by lstagner** [comment]
If there are no further comments I will merge this by the end of the day and update the fidasim/dev install on iris

**Comment by shaunhaskey** [comment]
@lstagner I'm trying to implement the required changes in my workflows to use this branch. Hopefully I will have run it with some sort of scan later today or tomorrow. If you are happy with it, I have no problem if you merge it now

**Comment by lstagner** [comment]
OK I will merge it now.

**Comment by lstagner** [comment]
Ok the fidasim/dev source code and tables have been updated. Just FYI I compiled the dev version with OpenMP instead of MPI so make sure you adjust your batch scripts accordingly or just use `submit_fidasim` which auto-magically handles the difference.

**Pull request merged**
