### PR TITLE
Restructuring of phi domain on the interpolation grid

### PR DESCRIPTION
**Pull request by alvin-garcia**
Hey Luke, please review this soon. We need to merge this change in. The FIDA and NPA data look fine. The neutron rate is slightly off. I think it is due to my inputs. Working on that now
mc_dist
phi_checks
oblique-ish
geo_top
pfida
fida
flux
pflux

...

### CODE REVIEW

**Comment by lstagner** [comment]
Shouldn't this be in your 3D FIDASIM branch which I haven't yet merged?

**Comment by alvin-garcia** [comment]
Yes, it is better to make the changes on ag/track. However, we need the phi domain adjustment ASAP and I don't know what the status is with regards to approval on the ag/track branch.

**Comment by lstagner** [comment]
Ok then

**Comment by lstagner** [comment]
Let me know when I can merge it.

**Pull request merged**
