### PR TITLE
added pgf90 compiling on venus

### PR DESCRIPTION
**Pull request by shaunhaskey**
Added a new pgf90 entry in the makefile, and instructions for environment variable settings on venus in README.md. To get it to compile with pgf90, I needed to modify the isnan's in fidasim.f90 - please check that you are happy with what I did. Currently, multiprocessing is not included; however, I ran a case on portal and a case on venus and the run times were 25mins and 29mins, so not a huge loss.

-Shaun

### CODE REVIEW

**Comment by lstagner** [comment]
This is great. Do you know why you couldn't get multi-processing to work with pgf90? Also does the ```submit_fidasim``` routine work on venus?

The only quibble I have with this is that we will have to bump up the minimum required version of gfortran to [5.1](https://gcc.gnu.org/gcc-5/changes.html#fortran) since they only just began supporting [IEEE modules](https://gcc.gnu.org/onlinedocs/gfortran/IEEE-modules.html) in April.

**Comment by shaunhaskey** [comment]
The ieee fix to allow pgf90 to compile it came from here : http://www.pgroup.com/userforum/viewtopic.php?t=2938&sid=cffc3856438189f0e3325126666dcc16 (pgf90 apparently doesn't like isnan because it is non standard). If there is any other alternative for getting isnan to work, I am more than happy to go with that.

Maybe the better longer term solution is to compile netcdf with ifort on venus and then use ifort instead of pgf90.  However, I ran into difficulties that seemed time consuming but not impossible to overcome with netcdf.

I ran into this error trying to compile with pgf90 with the -mp flag:
PGF90-S-0155-CYCLE may only apply to the innermost associated loop  (fidasim.f90: 3085)
  0 inform,   0 warnings,   1 severes, 0 fatal for halo
make: *** [fidasim.o] Error 2

However, I just tried using mpif90 on venus, and it seems to have compiled. Will see if it works soon.....

**Comment by lstagner** [comment]
Yes ultimately I think getting the Intel compiler to work on venus would be best. The portland compiler is super fast but also really fragile due to all the safety features they threw out for performance sake. This make it hard to debug if something goes wrong. The Intel compiler is not quite as fast but it is more reliable. If the Portland compiler is a Ferrari then the Intel Compiler is a Lexus. That being said we should always support gfortran as an alternative.

FIDASIM is not an MPI program so its strange to use mpif90 but so long as it works ¯\\_(ツ)_/¯.

**Comment by lstagner** [comment]
This is now moot due to #64

**Pull request closed without merging**
