### PR TITLE
Line intersection with the passive neutral grid bug fix

### PR DESCRIPTION
**Pull request by alvin-garcia**
@lstagner,

Please merge this into master. Thank you.

### CODE REVIEW

**Comment by lstagner** [comment]
Your fix assumes that the starting point is always going to be outside the plasma.

**Comment by lstagner** [comment]
additionally you are not actually calculating the intersection length of the LOS with the passive grid but with the plasma. It would be better to just take your time and find the edge case that caused the old version to fail.

**Comment by alvin-garcia** [comment]
@lstagner,

After modifying the new version a bit, the check for the starting point is reinserted and the issue with the edge condition is solved. Unless you have another comment, this branch is ready to be merged into the master branch.

Thanks.

**Comment by alvin-garcia** [comment]
Luke?

**Pull request merged**
