### PR TITLE
Cold D-alpha signal from passive neutral grid

### PR DESCRIPTION
**Pull request by alvin-garcia**
Not sure if this is exactly what is desired. The test case is not exactly reproducible, although I wonder if that is OK?

Screen Shot 2020-09-18 at 6 44 38 PM

P.S. inputs are located on Iris in my xpsi folder under FIDASIM/cold

### CODE REVIEW

**Comment by lstagner** [comment]
When I first added this functionality we didn't have the passive grid so in order for it to be accurate I had to extend the beam grid to cover the entire sightline. Its probably correct but to verify you have to extend the beam grid in the current version.

**Comment by lstagner** [comment]
Actually why is the new version less than the master version? I would think that essentially increasing the grid coverage would produce more signal.

**Comment by alvin-garcia** [comment]
Luke,

I made the beam grid large enough to cover the entire plasma in my original test. Thus, identical outputs are expected. However, the position definition wasn't correctly implemented in my first commit. It is now fixed and the outputs match. Please merge in the code. Thanks.

test_cold_comparison

**Comment by lstagner** [comment]
Great.

**Pull request merged**
