### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by alvin-garcia**
Hey Luke,

I think we should merge this branch in when FIDASIM 2.0 is ready. In the mean time, I think we should keep this branch open for any changes that pop into mind.

### CODE REVIEW

**Comment by alvin-garcia** [comment]
Please let me know if you think I should add anything else to this, otherwise merge this in.

**Comment by lstagner** [comment]
I think we should just merge this in sooner rather than later. We are getting to the point where a good number of people are using the development version. So having updated documentation is preferable. It also means that we should be getting ready for FIDASIM 2.0 soon, preferably by the end of August.

**Comment by alvin-garcia** [comment]
The documentation branch will continuously be updated as I develop new code. For the moment, it is safe to merge. However, you should expect more pull requests in the future.

**Comment by lstagner** [comment]
Thats fine just include documentation when making a PR for a new feature

**Comment by alvin-garcia** [comment]
Sounds good.

**Pull request merged**
