### PR TITLE
Update python preprocessing code for 3D geometry

### PR DESCRIPTION
**Pull request by alvin-garcia**
Luke,

Please merge.

### CODE REVIEW

**Comment by lstagner** [comment]
You should also change the IDL routines for feature parity

**Comment by alvin-garcia** [comment]
The IDL routines were changed a while back.

**Comment by lstagner** [comment]
No, the logic is now different. With this change the python version can accept 2D inputs while the IDL version cannot.

**Comment by alvin-garcia** [comment]
If I understand correctly, you are concerned about nphi in the IDL code. Fortunately, the conditional check I inserted into the python code is not needed in the IDL version. IDL ignores the last dimension of multi-dimensional arrays if it is equal to 1. The IDL code is stable.

**Comment by lstagner** [comment]
So it is. Got to brush up on my IDL again.

**Pull request merged**
