### PR TITLE
Python NUBEAM geometry bug fix

### PR DESCRIPTION
**Pull request by alvin-garcia**

### CODE REVIEW

**Comment by lstagner** [comment]
Does the IDL version need to change as well?

**Comment by BlehMaks** [comment]
> Does the IDL version need to change as well?

Probably no, but I do not have opportunity to check it. IDL version worked well for TCV tokamak case.

Also, what about the localization of spectral data?

**Comment by alvin-garcia** [comment]
@lstagner,

I modified the IDL code to match the Python code.

**Comment by alvin-garcia** [comment]
@BlehMaks,

The FIDASIM team discussed the issue and I am curious to learn more about it. The Python code is identical to the IDL code. If you find an issue with one code, the same issue should appear with the other code. Here is a nice figure from the thesis of one of our developers, @deyongl.
nubeam_geometry_FIDA_NPA_thesis

At the moment, I am convinced that our original code is correct. Would you be able to provide more details on why you think there is a bug? Also, uploading your inputs would help too.

**Comment by BlehMaks** [comment]
@alvin-garcia,

Thank you for your attention and response!

We have the following parameters of beam, NBI and FIDA systems are in the midplane cross section (z = 0):
RTCENA: 420 mm
XLBTNA: 3060 mm
XBZETA: 0 deg
XLBAPA: 1650 mm
NLCO: 1
NLJCCW: 1
So I supposed to get src = [3060 420 0] mm, aper_src = [1410 420 0] mm, axis = [-1 0 0] in machine coordinates and geometry like this:
Screenshot_18

Let's consider nubeam_geometry routine. According to it we should have phi_s = 0, and phi_a ~ 11 deg that is incorrect in my opinion. In this case we get src = [308.86890423   0.           0.        ] cm, axis = [-0.99071158  0.13598002  0.        ]

Also, output of prefida regarding to the NBI:
Screenshot_19

Here is what I get using the original code of nubeam_geometry (let's imagine that ellipses are circles):
Screenshot_20

Am I doing something wrong? If so, could you please explain to me what?

Thank you in advance!

Best regards,
Maksim

**Comment by alvin-garcia** [comment]
@BlehMaks,

If your vertical line in the graph corresponds to the red line (TRANSP axis) in @deyongl's figure, then it would seem that the mistake is with XBZETA. You defined it as 0 degrees, but it should be 82 degrees.

**Comment by BlehMaks** [comment]
@alvin-garcia,

Yes, you were right. I thought that NBI on our machine described correctly, but it was not. FIDASIM routine nubeam_geometry now works well for my case. 
Thank you very much for your help and response!

**Comment by alvin-garcia** [comment]
@BlehMaks,

Sounds good, thanks for letting us know.

**Pull request closed without merging**
