### PR TITLE
Optimize passive neutral grid creation

### PR DESCRIPTION
**Pull request by alvin-garcia**
Luke,

Please begin reviewing. The majority of the work is finished. I will let you know when to consider merging.

Thanks

Note: This PR addresses [Issue 167](https://github.com/D3DEnergetic/FIDASIM/issues/167)

### CODE REVIEW

**Comment by alvin-garcia** [comment]
OK merge.

**Comment by lstagner** [comment]
Does this fix the reported issue with LHD?

**Comment by lstagner** [comment]
Also has all tests passed?

**Comment by lstagner** [comment]
I'll merge this in by noon. If you have any objections let me know. I will also let the person from TCV know his issue has been fixed.

**Pull request merged**
