### PR TITLE
Generalized finding the plasma extrema part of making the passive grid

### PR DESCRIPTION
**Pull request by alvin-garcia**
@lstagner,

Please merge this in. I have tested it on NSTX inputs and good agreement is observed between OMP and MPI runs. There are minor discrepancies near the edge of the plasma for pFIDA, but I think that is expected.

bes1
bes2
fida_pfida1
fida_pfida2
halo_dcx1
halo_dcx2

### CODE REVIEW

**Comment by lstagner** [comment]
> There are minor discrepancies near the edge of the plasma for FIDA and pFIDA, but I think that is expected.

Can you explain why you think that is expected? What is causing the discrepancy?

**Comment by alvin-garcia** [comment]
The plasma and fast-ion density profiles have high upper and lower triangularity. Also, the cold neutral profile is practically a ring.

nn

The small discrepancy on chord 14 between OMP and MPI runs could be from slight differences with interpolation done in cells near the edge. The chords near the edge do not intersect much neutral or fast ion density. Therefore, the magnitude could be affected.

I ran FIDASIM again and chord 14 shows good agreement.

fida_pfida2_new

**Comment by lstagner** [comment]
Did you change anything between the first run and the second? Did you change the number of threads/processes? OpenMP and MPI should always agree.

**Comment by alvin-garcia** [comment]
You are right. The only change was that I allocated more memory on my second run, i.e. `-m 6G` to `-m 10G`. Maybe that did it...

**Comment by lstagner** [comment]
can you reproduce the discrepancy?

**Comment by lstagner** [comment]
I'll merge this in for now but I still want to know what caused the discrepancy in the OMP vs MPI version

**Pull request merged**
