### PR TITLE
Replace OpenCoArrays with pure MPI

### PR DESCRIPTION
**Pull request by sfiligoi**
Since basically only co_sum was used out of the OpenCoArrays library,
I re-implemented it using pure MPI, which is much widely supported.
A dedicated fidempi module has been created to incapsulate all of the MPI details.

Some minor refactoring of the code was needed to account for the other differences.

The code has been verified to work with both gcc7 and ifort2017.

### CODE REVIEW

**Comment by lstagner** [comment]
Looks good! Does it also work with the pgf90 compiler?

**Comment by lstagner** [comment]
Also could you tell me which modules you used. When this is merged I need to change the modulefile so that it will compile with intel.

**Comment by sfiligoi** [comment]
On iris I used
module load gcc7
module load ifort/ifort2017
module load mpich/3.2-ifort2017
export FC=ifort
export CC=gcc
export CXX=g++

**Comment by sfiligoi** [comment]
And the PGi version seems to work fine, too.

iris setup:
module load gcc7
module load pgf/17.7
module load mpich/3.2-pgf17.7
export FC=pgf90
export CC=pgcc
export CXX=pgc++

**Comment by sfiligoi** [comment]
There may be some problems with the birth file handling... investigating

**Comment by sfiligoi** [comment]
Birth profile writing seems to work now

**Comment by lstagner** [comment]
Let me know when you think you are done and I'll merge this in.

**Comment by sfiligoi** [comment]
I think it is ready to be merged.
I have tested all the config combinations I could think of.

**Comment by lstagner** [comment]
So just starting from a clean slate I am unable to build HDF5 with settings you provided. It cannot be built without the intel C and C++ compilers as well. I'm actually surprised HDF5 worked at all when you set FC to ifort.

**Comment by sfiligoi** [comment]
I had disabled the c++ option when builidng hdf5. Not needed.
iris also has a pre-built version of hdf5, which I also tested against.
Was planning a separate patch for that.
hdf5/1.8.19-mpich3.2-ifort2017
hdf5/1.8.19-mpich3.2-pgf17.7

**Comment by lstagner** [comment]
I would like to keep using the included hdf5 if possible. Could we not just get the intel C and C++ compilers on Iris?

removing the `--enable-cxx` didn't fix the problem. I get the following error during the build
```
...
checking for config linux-gnu... found
compiler 'gcc' is GNU gcc-7.1.0
compiler 'ifort' is Intel ifort-17.0.4.196
checking for config ./config/site-specific/host-irisc.cluster... no
checking for config ./config/site-specific/host-cluster... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/home/stagnerl/FIDASIM/deps/hdf5-1.8.16':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Pull request merged**
