### PR TITLE
Changed shot from int to long in prefida.pro

### PR DESCRIPTION
**Pull request by shaunhaskey**
@lstagner @bgrierson21 int only allows +-32k, need more for DIII-D shots

### CODE REVIEW

**Comment by lstagner** [comment]
Does this break the test cases?

**Comment by shaunhaskey** [comment]
Yes, it does because shot:1 apparently uses an int... should I just change the shot to a long in the test case?

**Comment by lstagner** [comment]
Yes, its probably not a good idea to break the test cases.

**Comment by shaunhaskey** [comment]
All done. I'll leave the merge to you if you are happy.

**Comment by lstagner** [comment]
Merged. Thanks. BTW its a good idea to have the test cases stored somewhere so its easy to see if you have broken anything.

**Pull request merged**
