### PR TITLE
3D capabilities added to pre-FIDASIM code 

### PR DESCRIPTION
**Pull request by alvin-garcia**
Luke,

Hold on merging, I'm going to make the necessary changes to the IDL scripts.

### CODE REVIEW

**Comment by alvin-garcia** [comment]
OK now merge please.

**Comment by lstagner** [comment]
For the IDL routines you have a check for whether nphi was submitted. I don't see a similar check for the python routines.

**Comment by alvin-garcia** [comment]
OK, working on it. Is psi supposed to be a kw argument in read_geqdsk? It is not defined in utils.py

**Comment by lstagner** [comment]
I made some changes to read_geqdsk today. Psi is no longer a keyword argument. It was replaced with `poloidal`

**Comment by lstagner** [comment]
Is this good to go now?

**Comment by alvin-garcia** [comment]
Almost... 3D changes are in place, but I have to review the changes you made to the IDL code and make similar changes to the python code. At the moment, the python preprocessing code will not run due to the recent psi related changes.

**Comment by lstagner** [comment]
You should rebase against master. I fixed a python bug yesterday in commit 2c13b9f687d892cf399144f2ad450233389c126f

**Comment by alvin-garcia** [comment]
Awesome, it is working. Merge it in.

**Pull request merged**
