### PR TITLE
Work done while tracking down FLR difference

### PR DESCRIPTION
**Pull request by lstagner**
This is a collection of work that I did while tracking down an issue with large larmor radii. This adds

* Second order correction to Larmor radius
* Switch to turn off FLR
* Faster reading of particle distributions
* Misc. fixes

The result of these changes is summarized in the figure below (NSTX, blue shifted)
fbm_flr

As you can see the second order correction is pretty small.

@deyongl

### CODE REVIEW

**Comment by deyongl** [comment]
@lstagner  Regarding the correction on gyro-step, it seem you made some approximation (e.g. ignoring curvature term and assuming B is proportional to 1/R ) for the formula A(3) in Belova's POP2003 paper. Why do not calculate the terms in second bracket in A(3) numerically without the above assumptions?  In the code, we already know the local B field and fast ion velocity vector. Please correct me if I miss anything.

**Comment by lstagner** [comment]
I didn't include it for two reasons.

1. Laziness. I would of had to calculates gradients of the magnetic field
2. and it says in the paper the terms in the last bracket are not needed.

>The last two terms in Eq. (A3) are the second-order corrections,
of which only the first is needed, since $$ \hat{b} \cdot \Del \phi = 0$$

**Comment by deyongl** [comment]
All the terms in the first bracket in  Equation A(3) can be calculated numerically without the assumption that B is proportional to 1/R. Since Spherical Tokomak has low field and large magnetic shield, both the gradient B term and curvature B term can contribute to the Larmor-radius correction. One example is shown below.

[FLR.pdf](https://github.com/D3DEnergetic/FIDASIM/files/430157/FLR.pdf)

I have implemented this in my local FIDAsim version.

**Comment by lstagner** [comment]
Thats great. Once you feel its ready for public consumption open a pull request against master.

How does it compare against experimental data with your fix?

**Comment by deyongl** [comment]
I have compared simulated and measured FIDA spatial profiles for a few cases from NSTX/NSTX-U. In one case, they get reasonable agreement in peak position. In some other cases, there is still relatively large discrepancy. One example is shown below, which is the case shown in Bill's 2016 NF paper. The peak of the simulated FIDA spatial profile is ~5cm inside the measured peak.

fida_nstx
Figure in Heidbrink's 2016 NF paper


fidasim
Comparison of FIDA spatial profile and magnitude


fidasim_norm
Comparison of normalized FIDA spatial profile

**Comment by lstagner** [comment]
@deyongl How is your PR coming along?

**Pull request merged**
